plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = false

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', rootProject.project('common:').file('src/generated/resources/').getAbsolutePath(), '--existing',
                    rootProject.project('common:').file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    compileOnly project(":common")

    compileOnly group: 'org.jetbrains',name:'annotations',version: '24.1.0'
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.1"))
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    modImplementation("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    modImplementation("net.tslat.smartbrainlib:SmartBrainLib-forge-${minecraft_version}:${project.sbl_version}")
 //   modImplementation(jarJar("com.nyfaria.nyfsguilib:nyfsguilib-forge-${minecraft_version}:${ngl_version}"))
    modImplementation jarJar('mysticdrew:common-networking-forge:1.0.5-1.20.1')
    modImplementation "earth.terrarium.botarium:botarium-forge-1.20.1:2.3.4"
    modImplementation "dev.architectury:architectury-forge:$architectury_api_version"
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}
