plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    mcpVersion = minecraft_version
    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    api project(":nublar-gui")

    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    compileOnly group: 'org.jetbrains',name:'annotations',version: '24.1.0'
    compileOnlyApi 'net.minecraftforge:mergetool-api:1.0'

    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-common:${project.forge_config_api_port_version}"
    implementation 'com.moandjiezana.toml:toml4j:0.7.2'
    implementation "net.tslat.smartbrainlib:SmartBrainLib-common-${project.minecraft_version}:${project.sbl_version}"
    compileOnly "software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}"
  //  implementation ("com.nyfaria.nyfsguilib:nyfsguilib-common-${minecraft_version}:${ngl_version}") {transitive = false}
    implementation 'mysticdrew:common-networking-common:1.0.3-1.20.1'
    implementation "earth.terrarium.botarium:botarium-forge-1.20.1:2.3.4"
   // modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    compileOnly "dev.architectury:architectury-forge:$rootProject.architectury_api_version"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'
artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    sourceSets.main.resources.sourceDirectories.forEach {
        commonResources it
    }
}
